In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#  1. LABEL ENCODING

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
from  sklearn import preprocessing

In [5]:
le = preprocessing.LabelEncoder()
le.fit([1,2,2,6,10,6,10,2])

LabelEncoder()

In [6]:
le.classes_

array([ 1,  2,  6, 10])

In [8]:
le.transform([1,2,2,6,10,6,10,2])

array([0, 1, 1, 2, 3, 2, 3, 1], dtype=int64)

In [11]:
le.inverse_transform([0, 1, 1, 2, 3, 2, 3, 1])

array([ 1,  2,  2,  6, 10,  6, 10,  2])

In [16]:
le.fit(["paris","paris","tokyo","amsterdam",'tokyo'])

LabelEncoder()

In [17]:
list(le.classes_)

['amsterdam', 'paris', 'tokyo']

In [18]:
le.transform(['amsterdam', 'paris', 'tokyo','tokyo'])

array([0, 1, 2, 2], dtype=int64)

In [19]:
list(le.inverse_transform([2,2,1]))

['tokyo', 'tokyo', 'paris']

In [18]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [21]:
bridge_types = ("arch","beam",'truss','cantiliver','tied arch','suspension','cable','arch','beam')
bridge_df = pd.DataFrame(bridge_types,columns = ["Bridge_Types"])

In [22]:
bridge_df

Bridge_Types
0         arch
1         beam
2        truss
3   cantiliver
4    tied arch
5   suspension
6        cable
7         arch
8         beam

In [23]:
labelencoder = LabelEncoder()

In [24]:
bridge_df['bridge_types_cat'] = labelencoder.fit_transform(bridge_df["Bridge_Types"])
bridge_df

Bridge_Types  bridge_types_cat
0         arch                 0
1         beam                 1
2        truss                 6
3   cantiliver                 3
4    tied arch                 5
5   suspension                 4
6        cable                 2
7         arch                 0
8         beam                 1

In [11]:
import pandas as pd
import numpy as np
    


In [12]:
subject = ["physics",'chemistry','math','biology']*2
print(subject)

['physics', 'chemistry', 'math', 'biology', 'physics', 'chemistry', 'math', 'biology']


In [13]:
import random
marks = [random.randint(35,100) for i in range(8)]

In [14]:
marks

[37, 87, 85, 53, 65, 53, 96, 44]

In [15]:
tenth = pd.DataFrame({"Subject":subject,"Marks":marks})
tenth

Subject  Marks
0    physics     37
1  chemistry     87
2       math     85
3    biology     53
4    physics     65
5  chemistry     53
6       math     96
7    biology     44

In [19]:
tenth["Sub_num"] = labelencoder.fit_transform(tenth["Subject"])
tenth

NameError: name 'labelencoder' is not defined

In [ ]:
unisub=list(tenth["Subject"].value_counts().index)

In [ ]:
unisort=sorted(unisub)

In [ ]:
unisort

In [ ]:
maping = range(4)

In [42]:
for i,j  in zip(unisort,maping):
    print(f"for the subject {i},the mapped value is {j}")

for the subject biology,the mapped value is 0
for the subject chemistry,the mapped value is 1
for the subject math,the mapped value is 2
for the subject physics,the mapped value is 3


In [43]:
new ={}
for i ,j in zip(unisort,maping):
    new[i] = j


In [44]:
print(new)

{'biology': 0, 'chemistry': 1, 'math': 2, 'physics': 3}


In [48]:
tenth["manually_mapped"] = np.where(tenth["Subject"] == "biology",0, tenth["manually_mapped"])
tenth["manually_mapped"] = np.where(tenth["Subject"] == "chemistry",1, tenth["manually_mapped"])
tenth["manually_mapped"] = np.where(tenth["Subject"] == "math",2 tenth["manually_mapped"])
tenth["manually_mapped"] = np.where(tenth["Subject"] == "physics",3, tenth["manually_mapped"])


SyntaxError: invalid syntax (<ipython-input-48-837ac51be6ab>, line 3)

In [2]:
import pandas as pd

In [3]:
df= pd.read_csv("F:\Machine_learning\Social_Network_Ads.csv")

In [4]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
df["Gender"].value_counts()

Female    204
Male      196
Name: Gender, dtype: int64

In [6]:
len(df["Gender"].value_counts())

2

In [7]:
dummies = pd.get_dummies(df["Gender"])

In [8]:
dummies.head(10)

Female  Male
0       0     1
1       0     1
2       1     0
3       1     0
4       0     1
5       0     1
6       1     0
7       1     0
8       0     1
9       1     0